name: Deploy HTML Prep

description: Prepare static HTML for GitHub Pages deployment.

inputs:
  source:
    description: Path to the HTML file to publish.
    required: false
    default: docs/minecraft-plugin-hebrew.html
  output:
    description: Directory to place the published site.
    required: false
    default: dist

runs:
  using: composite
  steps:
    - name: Prepare output directory
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "${{ inputs.output }}"
    - name: Copy HTML as index
      shell: bash
      run: |
        set -euo pipefail
        cp "${{ inputs.source }}" "${{ inputs.output }}/index.html"
    - name: Copy output assets
      shell: bash
      run: |
        set -euo pipefail
        if [[ -d "output" ]]; then
          cp -R output/. "${{ inputs.output }}/"
        fi
        # Copy image assets from docs to the output root
        if [[ -d "docs" ]]; then
          find docs -type f \( -name "*.svg" -o -name "*.webp" -o -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" \) -exec cp {} "${{ inputs.output }}/" \;
        fi
    - name: Disable Jekyll
      shell: bash
      run: |
        set -euo pipefail
        touch "${{ inputs.output }}/.nojekyll"
