name: Generate Mods List

description: Scans mods folder and injects mod list into HTML before תקציר section.

inputs:
  mods-folder:
    description: Path to the mods folder to scan.
    required: false
    default: mods
  html-file:
    description: Path to the HTML file to modify.
    required: false
    default: docs/minecraft-plugin-hebrew.html

runs:
  using: composite
  steps:
    - name: Generate mods list and inject into HTML
      shell: bash
      run: |
        set -euo pipefail
        
        MODS_FOLDER="${{ inputs.mods-folder }}"
        HTML_FILE="${{ inputs.html-file }}"
        
        echo "Scanning mods folder: $MODS_FOLDER"
        
        # Check if mods folder exists
        if [ ! -d "$MODS_FOLDER" ]; then
          echo "Warning: Mods folder does not exist: $MODS_FOLDER"
          MOD_LIST_HTML="<li>אין מודים זמינים כרגע</li>"
        else
          # Find all .jar files in the mods folder using safer iteration
          MOD_LIST_HTML=""
          JAR_COUNT=0
          while IFS= read -r -d '' jar_file; do
            filename=$(basename "$jar_file")
            echo "  - $filename"
            MOD_LIST_HTML="${MOD_LIST_HTML}<li><code>$filename</code></li>"
            JAR_COUNT=$((JAR_COUNT + 1))
          done < <(find "$MODS_FOLDER" -maxdepth 1 -name "*.jar" -type f -print0 | sort -z)
          
          if [ $JAR_COUNT -eq 0 ]; then
            echo "No JAR files found in $MODS_FOLDER"
            MOD_LIST_HTML="<li>אין מודים זמינים כרגע</li>"
          else
            echo "Found $JAR_COUNT JAR file(s)"
          fi
        fi
        
        # Create the new card HTML
        NEW_CARD=$(cat <<EOF
    <section class="card">
      <h2>רשימת מודים זמינים</h2>
      <p>המודים הבאים זמינים להורדה:</p>
      <ul>
        ${MOD_LIST_HTML}
      </ul>
    </section>

EOF
)
        
        # Create a temporary file
        TEMP_FILE=$(mktemp)
        
        # Insert the new card before the "תקציר" section
        # We look for the opening tag of the section that contains תקציר
        INSERTION_RESULT=$(awk -v new_card="$NEW_CARD" '
        BEGIN { inserted = 0 }
        /<section class="card">/ {
          # Store the line
          line = $0
          # Read the next line and check for errors
          if ((getline next_line) > 0) {
            # Check if next section has תקציר
            if (next_line ~ /<h2>תקציר<\/h2>/) {
              # Print the new card before this section
              print new_card
              inserted = 1
            }
            # Print both lines
            print line
            print next_line
          } else {
            # getline failed, just print the current line
            print line
          }
          next
        }
        { print }
        END { print "INSERTED=" inserted > "/dev/stderr" }
        ' "$HTML_FILE" 2>&1 > "$TEMP_FILE")
        
        # Check if insertion happened
        if ! echo "$INSERTION_RESULT" | grep -q "INSERTED=1"; then
          echo "Error: Failed to inject mods list - תקציר section not found"
          rm -f "$TEMP_FILE"
          exit 1
        fi
        
        # Replace the original file
        mv "$TEMP_FILE" "$HTML_FILE"
        
        echo "Successfully injected mods list into $HTML_FILE"
